### ISSUE TITLE
Transaction Fee calculation

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-explorer-IPFS#5]
Implement the mechanism to calculate the reasonable/optimal transaction fee for the transactions that are being created on the wallet at this particular moment. 

In other words the client need to know what should be the transaction fee value when  creating transaction. So that information should be delivered to the client from IPFS.

When implementing make sure that our implementation can be easily used by other developers. They key terms is "easily". we want other developer to adopt/improve the solution that we implement

**Comment by nk-the-crazy** [comment]
Used BCOIN and BCASH libraries API to calculate Fee and store to IPFS. (Setup Bcoin and Bcash servers).
